import type React from "react"
import { Car, DollarSign, LayoutDashboard, Settings, Star, Shield, Zap } from "lucide-react"

export interface CarData {
  id: string
  name: string
  description: string
  price: number
  discount?: number
  imageSrc: string
  imageAlt: string
  type: string
  category: string
  location: string
  year: number
  mainFeatures: { name: string; icon: React.ElementType }[]
  fuelType?: string
  mileage?: string
  transmission?: string
}

const allCars: CarData[] = [
  // Existing 8 Cars
  {
    id: "1",
    name: "Ferrari 488 GTB",
    description: "A high-performance sports car with a powerful V8 engine and stunning design.",
    price: 36000000,
    discount: 1000000,
    imageSrc: "/images/ferrari-488-gtb.png",
    imageAlt: "Red Sports Car",
    type: "Sports",
    category: "Sports",
    location: "Mumbai",
    year: 2022,
    mainFeatures: [
      { name: "V8 Twin-Turbo Engine", icon: Zap },
      { name: "0-100 km/h in 3.0s", icon: Car },
      { name: "Carbon Ceramic Brakes", icon: Shield },
    ],
    fuelType: "Petrol",
    mileage: "8 kmpl",
    transmission: "Automatic",
  },
  {
    id: "2",
    name: "Honda City",
    description: "A reliable and fuel-efficient sedan, perfect for city driving and long commutes.",
    price: 1200000,
    discount: 50000,
    imageSrc: "/images/honda-city.png",
    imageAlt: "Blue Sedan Car",
    type: "Sedan",
    category: "Sedan",
    location: "Delhi",
    year: 2023,
    mainFeatures: [
      { name: "i-VTEC Engine", icon: Zap },
      { name: "Spacious Cabin", icon: LayoutDashboard },
      { name: "Excellent Fuel Economy", icon: DollarSign },
    ],
    fuelType: "Petrol",
    mileage: "18 kmpl",
    transmission: "Manual/Automatic",
  },
  {
    id: "3",
    name: "Mahindra XUV700",
    description: "A feature-packed SUV offering comfort, safety, and powerful performance.",
    price: 2000000,
    discount: 75000,
    imageSrc: "/images/mahindra-xuv700.png",
    imageAlt: "Black SUV Car",
    type: "SUV",
    category: "SUV",
    location: "Bangalore",
    year: 2023,
    mainFeatures: [
      { name: "AdrenoX Infotainment", icon: LayoutDashboard },
      { name: "ADAS Features", icon: Shield },
      { name: "All-Wheel Drive", icon: Settings },
    ],
    fuelType: "Petrol/Diesel",
    mileage: "15 kmpl",
    transmission: "Manual/Automatic",
  },
  {
    id: "4",
    name: "Tata Nexon EV",
    description: "India's best-selling electric SUV, offering great range and modern features.",
    price: 1500000,
    discount: 0,
    imageSrc: "/images/tata-nexon-ev.png",
    imageAlt: "White Electric Car",
    type: "Electric",
    category: "Electric",
    location: "Pune",
    year: 2023,
    mainFeatures: [
      { name: "312 km Range (ARAI)", icon: Car },
      { name: "Fast Charging Support", icon: DollarSign },
      { name: "ZConnect Connected Car Tech", icon: LayoutDashboard },
    ],
    fuelType: "Electric",
    mileage: "312 km",
    transmission: "Automatic",
  },
  {
    id: "5",
    name: "Maruti Suzuki Swift",
    description: "A popular hatchback known for its peppy engine and agile handling.",
    price: 800000,
    discount: 20000,
    imageSrc: "/images/maruti-suzuki-swift.png",
    imageAlt: "Silver Hatchback Car",
    type: "Hatchback",
    category: "Hatchback",
    location: "Chennai",
    year: 2023,
    mainFeatures: [
      { name: "K12C Engine", icon: Settings },
      { name: "Lightweight Design", icon: Car },
      { name: "Great Fuel Efficiency", icon: DollarSign },
    ],
    fuelType: "Petrol",
    mileage: "22 kmpl",
    transmission: "Manual/Automatic",
  },
  {
    id: "6",
    name: "Ford Mustang (1967)",
    description: "An iconic American muscle car, a true classic for enthusiasts.",
    price: 7500000,
    discount: 250000,
    imageSrc: "/images/ford-mustang-1976.png",
    imageAlt: "Yellow Vintage Car",
    type: "Vintage",
    category: "Classic",
    location: "Mumbai",
    year: 1967,
    mainFeatures: [
      { name: "V8 Power", icon: Zap },
      { name: "Classic Design", icon: Star },
      { name: "Collector's Item", icon: Shield },
    ],
    fuelType: "Petrol",
    mileage: "50,000 km",
    transmission: "Manual",
  },
  {
    id: "7",
    name: "BMW 3 Series",
    description: "A luxury sedan that combines performance with sophistication.",
    price: 4500000,
    discount: 150000,
    imageSrc: "/images/bmw-3-series.png",
    imageAlt: "White Luxury Sedan",
    type: "Luxury",
    category: "Luxury",
    location: "Delhi",
    year: 2023,
    mainFeatures: [
      { name: "TwinPower Turbo", icon: Zap },
      { name: "iDrive 7.0", icon: LayoutDashboard },
      { name: "Premium Interior", icon: Star },
    ],
    fuelType: "Petrol/Diesel",
    mileage: "12 kmpl",
    transmission: "Automatic",
  },
  {
    id: "8",
    name: "Hyundai i20",
    description: "A premium hatchback with modern features and excellent build quality.",
    price: 900000,
    discount: 30000,
    imageSrc: "/images/hyundai.png",
    imageAlt: "Red Hatchback Car",
    type: "Hatchback",
    category: "Hatchback",
    location: "Bangalore",
    year: 2023,
    mainFeatures: [
      { name: "SmartSense Features", icon: Shield },
      { name: "Connected Car Tech", icon: LayoutDashboard },
      { name: "Premium Design", icon: Star },
    ],
    fuelType: "Petrol",
    mileage: "20 kmpl",
    transmission: "Manual/Automatic",
  },

  // Newly Added 12 Cars
  {
    id: "9",
    name: "Audi Q5",
    description: "A sophisticated luxury SUV that blends performance with everyday usability.",
    price: 6500000,
    discount: 200000,
    imageSrc: "/images/audi-q7.png",
    imageAlt: "White Audi Q5 SUV",
    type: "Luxury",
    category: "SUV",
    location: "Mumbai",
    year: 2023,
    mainFeatures: [
      { name: "Quattro All-Wheel Drive", icon: Settings },
      { name: "Virtual Cockpit Display", icon: LayoutDashboard },
      { name: "Matrix LED Headlights", icon: Star },
    ],
    fuelType: "Petrol",
    mileage: "13 kmpl",
    transmission: "Automatic",
  },
  {
    id: "10",
    name: "Mercedes-Benz C-Class",
    description: "The 'Baby S-Class' offers unparalleled luxury and cutting-edge tech in the sedan segment.",
    price: 6000000,
    discount: 250000,
    imageSrc: "/images/mercedez-c-class.png",
    imageAlt: "Black Mercedes-Benz C-Class Sedan",
    type: "Luxury",
    category: "Sedan",
    location: "Delhi",
    year: 2023,
    mainFeatures: [
      { name: "MBUX Infotainment", icon: LayoutDashboard },
      { name: "Plush Interiors", icon: Star },
      { name: "Agile Handling", icon: Car },
    ],
    fuelType: "Petrol/Diesel",
    mileage: "16 kmpl",
    transmission: "Automatic",
  },
  {
    id: "11",
    name: "Jeep Compass",
    description: "A rugged and capable SUV with iconic styling and a premium interior.",
    price: 2200000,
    discount: 80000,
    imageSrc: "/images/jeep-compass.png",
    imageAlt: "Grey Jeep Compass SUV",
    type: "SUV",
    category: "SUV",
    location: "Pune",
    year: 2023,
    mainFeatures: [
      { name: "4x4 Capability", icon: Shield },
      { name: "Uconnect 5 System", icon: LayoutDashboard },
      { name: "Panoramic Sunroof", icon: Star },
    ],
    fuelType: "Petrol/Diesel",
    mileage: "14 kmpl",
    transmission: "Manual/Automatic",
  },
  {
    id: "12",
    name: "Kia Seltos",
    description: "A stylish and feature-rich SUV that has taken the market by storm.",
    price: 1800000,
    discount: 60000,
    imageSrc: "/images/kia-seltos.png",
    imageAlt: "Orange Kia Seltos SUV",
    type: "SUV",
    category: "SUV",
    location: "Hyderabad",
    year: 2023,
    mainFeatures: [
      { name: "BOSE Sound System", icon: Star },
      { name: "Ventilated Seats", icon: Settings },
      { name: "Smart Air Purifier", icon: Shield },
    ],
    fuelType: "Petrol/Diesel",
    mileage: "17 kmpl",
    transmission: "Manual/Automatic",
  },
  {
    id: "13",
    name: "MG Hector",
    description: "The 'Internet Inside' SUV with a massive touchscreen and spacious cabin.",
    price: 2100000,
    discount: 90000,
    imageSrc: "/images/mg-hector.png",
    imageAlt: "Red MG Hector SUV",
    type: "SUV",
    category: "SUV",
    location: "Ahmedabad",
    year: 2023,
    mainFeatures: [
      { name: "14-inch Touchscreen", icon: LayoutDashboard },
      { name: "AI Voice Assistant", icon: Zap },
      { name: "Spacious Legroom", icon: Car },
    ],
    fuelType: "Petrol/Diesel",
    mileage: "13 kmpl",
    transmission: "Automatic",
  },
  {
    id: "14",
    name: "Nissan Magnite",
    description: "A compact SUV offering bold design and great value for money.",
    price: 950000,
    discount: 40000,
    imageSrc: "/images/nissan-magnite.png",
    imageAlt: "Silver Nissan Magnite Compact SUV",
    type: "Compact",
    category: "SUV",
    location: "Kolkata",
    year: 2023,
    mainFeatures: [
      { name: "Turbo Engine Option", icon: Zap },
      { name: "Wireless CarPlay", icon: LayoutDashboard },
      { name: "Tech Pack", icon: Settings },
    ],
    fuelType: "Petrol",
    mileage: "20 kmpl",
    transmission: "Manual/Automatic",
  },
  {
    id: "15",
    name: "Porsche 911",
    description: "The quintessential sports car with timeless design and exhilarating performance.",
    price: 21000000,
    discount: 0,
    imageSrc: "/images/porche-911.png",
    imageAlt: "Yellow Porsche 911 Sports Car",
    type: "Sports",
    category: "Sports",
    location: "Mumbai",
    year: 2023,
    mainFeatures: [
      { name: "PDK Transmission", icon: Settings },
      { name: "Iconic Silhouette", icon: Star },
      { name: "Rear-Engine Layout", icon: Car },
    ],
    fuelType: "Petrol",
    mileage: "9 kmpl",
    transmission: "Automatic",
  },
  {
    id: "16",
    name: "Renault Kwid",
    description: "An entry-level hatchback with SUV-inspired looks and a digital instrument cluster.",
    price: 470000,
    discount: 15000,
    imageSrc: "/images/renault-kwid.png",
    imageAlt: "Blue Renault Kwid Hatchback",
    type: "Hatchback",
    category: "Hatchback",
    location: "Chennai",
    year: 2023,
    mainFeatures: [
      { name: "High Ground Clearance", icon: Shield },
      { name: "Digital Instrument Cluster", icon: LayoutDashboard },
      { name: "Budget Friendly", icon: DollarSign },
    ],
    fuelType: "Petrol",
    mileage: "22 kmpl",
    transmission: "Manual",
  },
  {
    id: "17",
    name: "Rolls-Royce Phantom",
    description: "The pinnacle of automotive luxury, offering a bespoke and serene travel experience.",
    price: 100000000,
    discount: 0,
    imageSrc: "/images/rolls-roys-phantom.png",
    imageAlt: "Black Rolls-Royce Phantom Luxury Car",
    type: "Luxury",
    category: "Luxury",
    location: "Delhi",
    year: 2023,
    mainFeatures: [
      { name: "Starlight Headliner", icon: Star },
      { name: "Magic Carpet Ride", icon: Car },
      { name: "Coach Doors", icon: Settings },
    ],
    fuelType: "Petrol",
    mileage: "7 kmpl",
    transmission: "Automatic",
  },
  {
    id: "18",
    name: "Skoda Slavia",
    description: "A dynamic sedan with a powerful TSI engine and a high safety rating.",
    price: 1600000,
    discount: 65000,
    imageSrc: "/images/skoda-slavia.png",
    imageAlt: "Red Skoda Slavia Sedan",
    type: "Sedan",
    category: "Sedan",
    location: "Pune",
    year: 2023,
    mainFeatures: [
      { name: "1.5L TSI Engine", icon: Zap },
      { name: "5-Star Safety Rating", icon: Shield },
      { name: "Large Boot Space", icon: LayoutDashboard },
    ],
    fuelType: "Petrol",
    mileage: "19 kmpl",
    transmission: "Manual/Automatic",
  },
  {
    id: "19",
    name: "Toyota Innova Crysta",
    description: "The undisputed king of MPVs, known for its reliability, comfort, and resale value.",
    price: 2500000,
    discount: 50000,
    imageSrc: "/images/toyota-innova-crysta.png",
    imageAlt: "White Toyota Innova Crysta MPV",
    type: "SUV", // Using SUV as the closest category type
    category: "SUV",
    location: "Bangalore",
    year: 2023,
    mainFeatures: [
      { name: "Captain Seats", icon: Star },
      { name: "Unmatched Reliability", icon: Shield },
      { name: "Spacious 7-seater", icon: Car },
    ],
    fuelType: "Diesel",
    mileage: "12 kmpl",
    transmission: "Manual",
  },
  {
    id: "20",
    name: "Volkswagen Virtus",
    description: "A sophisticated sedan with German engineering, offering a fun-to-drive experience.",
    price: 1700000,
    discount: 70000,
    imageSrc: "/images/volkswagen-virtus.png",
    imageAlt: "Yellow Volkswagen Virtus Sedan",
    type: "Sedan",
    category: "Sedan",
    location: "Mumbai",
    year: 2023,
    mainFeatures: [
      { name: "GT Performance Line", icon: Zap },
      { name: "Digital Cockpit", icon: LayoutDashboard },
      { name: "Solid Build Quality", icon: Shield },
    ],
    fuelType: "Petrol",
    mileage: "18 kmpl",
    transmission: "Manual/Automatic",
  },
]

export default allCars
